---

- name: Update .htaccess
  block:
    - name: Make .htaccess writable
      file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        mode: g+w
      listen: nextcloud update htaccess
    - name: Update .htaccess file
      command: ./occ maintenance:update:htaccess --no-interaction
      args:
        chdir: "{{ nextcloud_installation_dir }}"
      listen: nextcloud update htaccess
      become: true
      become_user: "{{ nextcloud_file_owner }}"
    - name: Make .htaccess unwritable again
      file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        mode: g-w
      listen: nextcloud update htaccess

- name: Set permissions on downloaded apps
  file:
    path: "{{ nextcloud_installation_dir }}/apps/"
    mode: u=rwX,g=rX,o=rX
    owner: "{{ nextcloud_file_owner }}"
    group: "{{ nextcloud_file_owner }}"
    state: directory
    recurse: true
  listen: set app files permissions

- name: Set file permissions on Nextcloud files
  block:
    - name: Find Nextcloud files
      find:
        path: "{{ nextcloud_installation_dir }}"
        file_type: any
        register: nextcloud_installation_files
      listen: nextcloud set secure file permissions
    - name: Set permissions on directories
      file:
        path: "{{ item.path }}"
        owner: "{{ nextcloud_file_owner }}"
        group: "{{ nextcloud_file_owner }}"
        mode: 0o750
        state: directory
        recurse: true
      loop: >-
        {{
          nextcloud_installation_files.files
          | selectattr('isdir')
          | list
        }}
      listen: nextcloud set secure file permissions
    # For files, we are using `shell` as `file` with a loop would take ages
    # to complete.
    - name: Set ownership on files
      command: >-
        find "{{ nextcloud_installation_dir }}"
          -type f
          -exec chown {{
                    nextcloud_file_owner }}:{{ nextcloud_file_owner }} {} \;
          -exec chmod 0640 {} \;
      changed_when: false
      listen: nextcloud set secure file permissions
    - name: Set permissions on installation directory
      file:
        path: "{{ nextcloud_installation_dir }}"
        owner: root
        group: "{{ nextcloud_file_owner }}"
        mode: 0o750
        state: directory
      listen: nextcloud set secure file permissions
    - name: Set permissions on htaccess file
      file:
        path: "{{ nextcloud_installation_dir }}/.htaccess"
        owner: root
        group: "{{ nextcloud_file_owner }}"
        mode: 0o644
      listen: nextcloud set secure file permissions
